# Java Maven CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2
jobs:
  build-and-test:

    working_directory: ~/trakt-java

    docker:
    - image: circleci/openjdk:8-jdk

    steps:

    - checkout

    - restore_cache: # restore the saved cache after the first run or if `pom.xml` has changed
        key: trakt-java-{{ checksum "pom.xml" }}

    - run: mvn --batch-mode -show-version --errors dependency:go-offline # gets the project dependencies

    - save_cache: # saves the project dependencies
        paths:
        - ~/.m2
        key: trakt-java-{{ checksum "pom.xml" }}

    - run: mvn --batch-mode -show-version --errors package # run the actual tests

    - store_test_results: # uploads the test metadata so that it can show up in the CircleCI dashboard.
        path: target/surefire-reports

workflows:
  version: 2
  build-and-test:
    jobs:
      - build-and-test
